### PR TITLE
Rebuild to receive updated run_exports from fontconfig

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Context: 
* https://github.com/conda-forge/fontconfig-feedstock/pull/47/files
* https://github.com/conda-forge/r-base-feedstock/issues/91

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Ready for review / merge :)

**Comment by dbast** [comment]
Ping :)

**Comment by pkgw** [comment]
Thanks!

**Pull request merged**
