### PR TITLE
Add Windows build using meson

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Required dependency for `gtk3` on Windows.

### CODE REVIEW

**Comment by ryanvolz** [comment]
Waiting on build for `fribidi` (https://github.com/conda-forge/fribidi-feedstock/pull/8).

**Comment by pkgw** [comment]
@conda-forge-admin, please restart ci

fribidi has been bumped.

**Comment by pkgw** [comment]
@ryanvolz Windows failed here ... besides a gobject-introspection issue, note also the error a few lines above: `ninja: fatal: ReadFile: The handle is invalid.` — haven't seen that before.

**Comment by ryanvolz** [comment]
> @ryanvolz Windows failed here ... besides a gobject-introspection issue, note also the error a few lines above: `ninja: fatal: ReadFile: The handle is invalid.` — haven't seen that before.

Yes, it looks to be the same problem caused by the `conda-build` Windows prefix detection bug that's affecting `gobject-introspection` and causing build failures with `atk` and `gdk-pixbuf` (https://github.com/conda-forge/gobject-introspection-feedstock/issues/19).

I *think* the `ninja: fatal: ReadFile: The handle is invalid.` is related because it is present for all of them and isn't an issue building locally with `conda-build=3.18.11`.

**Review by pkgw — APPROVED** [review]
Anyway, changes look OK pending working through the last issues.

**Comment by pkgw** [comment]
Closes #18.

**Pull request merged**
