### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.10 and pinning 2018.08.05

### PR DESCRIPTION
**Pull request by bgruening**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @ocefpaf

**Review by ocefpaf — APPROVED** [review]

**Comment by bgruening** [comment]
Grml: `ImportError: /home/conda/feedstock_root/build_artifacts/pango_1533510192727/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/_giscanner.so: undefined symbol: PyUnicode_AsUTF8String`

**Comment by bgruening** [comment]
Ah, everything (cairo, glib ...) is coming from `defaults`.

**Comment by ocefpaf** [comment]
> Ah, everything (cairo, glib ...) is coming from `defaults`.

That sucks :-(

BTW, I would probably wait for the compilers and `.la` migrations first before sending these PRs. That way we can start with a fresh set of packages that will be used in the long term.

PS: we need to identify the reason for these packages from `defaults` and fix that (it may be cf is outdated, or the use of features, or just coda channel reference bug/feature that we can't do anything about :smile:)

**Comment by bgruening** [comment]
> PS: we need to identify the reason for these packages from defaults and fix that (it may be cf is outdated, or the use of features, or just coda channel reference bug/feature that we can't do anything about smile)

I think it was the outdated cairo pkg. See https://github.com/conda-forge/cairo-feedstock/pull/40

> BTW, I would probably wait for the compilers and .la migrations first before sending these PRs.

The la file changes should be all merged isn't it? How long will the compiler changes take?

**Comment by pkgw** [comment]
I tried to rerun the build on Circle and it errored out due to some transient problem, but I ran the Linux build locally and it worked, so I think this PR should be OK now that our version of `cairo` has been updated.

**Comment by bgruening** [comment]
@pkgw it seems to run now. I restarted it again, but I do this is error:
`ImportError: /home/conda/feedstock_root/build_artifacts/pango_1533568489504/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/gobject-introspection/giscanner/_giscanner.so: undefined symbol: PyUnicode_AsUTF8String`

**Comment by bgruening** [comment]
On OSX I still see a few pkgs coming from `defaults`: https://travis-ci.org/conda-forge/pango-feedstock/builds/412432498#L358

**Comment by bgruening** [comment]
There are still multiple packages coming from defaults. My next guess would be to sync https://github.com/conda-forge/gobject-introspection-feedstock with anaconda-recipes and https://github.com/conda-forge/harfbuzz-feedstock/blob/master/recipe/meta.yaml#L32 to the new version.

ping @pkgw @mingwandroid - I assume pango is the reason we can not proceed with the R 3.5.1 PR.

**Comment by pkgw** [comment]
I think this is basically about a lot of deps not being caught up to freetype 2.9. Do we have a way to interrogate the current package set and figure out what needs to be taken care of?

**Comment by bgruening** [comment]
Ha, green! ping @conda-forge/pango for review and merge :)

**Comment by pkgw** [comment]
The Linux build pulled in `fontconfig` from `defaults`, but the underlying versions are the same so I am pretty sure that this is OK. I don't see any other issues. I can merge if there are no complaints.

**Comment by pkgw** [comment]
Looking at what got installed for the build, I think the depsolver needs to pull in `fontconfig` from `defaults` because the recent conda-forge packages require `libuuid >=2`, while version 1.0 is getting installed. So probably there is some other dep involved that still wants `libuuid` 1.0.

**Comment by pkgw** [comment]
New version of `xorg-libsm` [in prep](https://github.com/conda-forge/xorg-libsm-feedstock/pull/8) that should fix the aforementioned items. I'm pretty sure that a package built without the new xorg-libsm would be fine, but this should be quick to work through.

**Comment by pkgw** [comment]
👍

**Pull request merged**
