### PR TITLE
Bump to 1.48.3

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@isuruf Could you have a look at this OS X ARM failure? I migrated the build from auto tools to meson and it looks like it doesn't work anymore...

The windows build will be fixed when https://github.com/conda-forge/cairo-feedstock/pull/60 is merged in.

Thanks in advance!!

**Comment by pkgw** [comment]
I'm guessing that this issue might be something in Meson 0.57? It looks like you've derived this code from the GTK3 feedstock and I can't spot any differences between the two that should matter. But the most recent gtk3 builds are still using Meson 0.56.2, and this one's on Meson 0.57.1.

**Comment by pkgw** [comment]
And right, GTK3 forces the use of Meson 0.56; cf https://github.com/conda-forge/gtk3-feedstock/pull/26 .

**Comment by tschoonj** [comment]
Trying that now, I don't like pinning meson 😄

**Comment by pkgw** [comment]
> Trying that now, I don't like pinning meson

Yeah, we need to get the new version straightened out. I hope that Meson becomes a bit more stable — it feels like there's always some corner case to chase down when a new release comes out.

**Comment by pkgw** [comment]
Looks like you need to override `CXX`?

**Comment by tschoonj** [comment]
I expect this one will succeed, but please don't merge it in yet, as I want to see if I can get rid of the vs2019 dependency

**Comment by isuruf** [comment]
Thanks @tschoonj, @pkgw for figuring out the osx-arm64 build.

**Comment by tschoonj** [comment]
This is ready for a merge if there are no further comments.

**Comment by pkgw** [comment]
Thanks so much for your work on all of these upgrades @tschoonj!

**Pull request merged**
